import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../../styles/Home.module.css"

const Contact: NextPage = () => {
  return (
    <main>
      <Head>
        <title>{"Contact"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{"Contact"}</h1>
    </main>
  )
}

export default Contact
