import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { WithContext, LocalBusiness, PostalAddress } from "schema-dts"

const siteurl = "https://pacifique-habitat.vercel.app"
const sitename = "Pacifique Habitat"

const address: PostalAddress = {
  "@type": "PostalAddress",
  addressLocality: "Tahiti",
  postalCode: "98718",
  streetAddress: "998W+6W Puna'auia, Polynésie française",
  addressCountry: "PF",
  addressRegion: "Puna'auia",
}

const organization: WithContext<LocalBusiness> = {
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  url: siteurl,
  logo: `${siteurl}/assets/logo-112.png`,
  name: sitename,
  image: `${siteurl}/assets/logo-1080.png`,
  address,
  priceRange: "$$$$",
  telephone: "+689-40-832220",
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{sitename}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script type="application/ld+json">{JSON.stringify(organization)}</script>
      </Head>

      <main className={styles.main}>
        <h1>{sitename}</h1>
      </main>

      <footer className={styles.footer}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
