import type { NextPage } from "next"
import Head from "next/head"
import { sitename } from "@utils/schema"

const Home: NextPage = () => {
  return (
    <main>
      <Head>
        <title>{sitename}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>{sitename}</h1>
    </main>
  )
}

export default Home
